export const uiTimeouts = {
  pageReady: process.env.PLAYWRIGHT_REAL_BACKEND === 'true' ? 60_000 : 30_000,
  action: 15_000,
  toast: 30_000,
} as const;

export const loginSelectors = {
  page: '[data-testid="login-page"], .login-wrapper',
  form: '[data-testid="login-form"], .login-form-box',
  connectionSelect: '[data-testid="login-connection"], #login-connection',
  connectionEditButton: '[data-testid="login-connection-edit"], #login-connection-edit',
  userInput: '[data-testid="login-user"], #login-user',
  passwordInput: '[data-testid="login-password"], #login-pwd',
  submitButton: '[data-testid="login-submit"], #login-submit',
  treeModel: '[data-testid="login-model-tree"], #connection-modal-type-0',
  tableModel: '[data-testid="login-model-table"], #connection-modal-type-1',
  validationError: '.el-form-item__error',
} as const;

export const instanceManagementSelectors = {
  modal: '[data-testid="connection-modal"], #connection-modal',
  modalCloseButton: '#connection-modal .el-dialog__headerbtn',
  form: '[data-testid="connection-form"], #connection-modal .connection-detail-wrapper',
  list: '[data-testid="connection-list"], #connection-modal .list-box',
  listAddButton: '[data-testid="connection-list-add"], #connection-side-add',
  listRefreshButton: '[data-testid="connection-list-refresh"], #connection-side-refresh',
  listSearchInput: '[data-testid="connection-list-search"], #connection-list-input',
  listEmpty: '.list-empty-wrapper',
  draftItem: '[data-testid="connection-item-new"], #connection-item-new',
  connectionName: '[data-testid="connection-name"], #connection-modal-name',
  host: '[data-testid="connection-masterCluster-hostAndPortVOS-0-host"], [id="masterCluster.hostAndPortVOS-0-host"]',
  port: '[data-testid="connection-masterCluster-hostAndPortVOS-0-port"], [id="masterCluster.hostAndPortVOS-0-port"]',
  username: '[data-testid="connection-username"], #connection-modal-username',
  password: '[data-testid="connection-password"], #connection-modal-password',
  prometheusUrl: '[data-testid="connection-masterCluster-prometheusUrl-prometheus-url"], [id="masterCluster.prometheusUrl-prometheusUrl"]',
  prometheusAuth: '[data-testid="connection-masterCluster-prometheusUrl-prometheus-auth"]',
  prometheusUsername: '[data-testid="connection-masterCluster-prometheusUrl-prometheus-username"]',
  prometheusPassword: '[data-testid="connection-masterCluster-prometheusUrl-prometheus-password"]',
  standaloneType: '[data-testid="connection-type-standalone"], #connection-modal-type-0',
  defaultTreeModel: '[data-testid="connection-default-model-tree"], #connection-default-model-tree',
  saveButton: '[data-testid="connection-save"], #connection-modal-save',
  testButton: '[data-testid="connection-test"], #connection-modal-test',
  resetButton: '[data-testid="connection-reset"], #connection-modal-reset',
  validationError: '.el-form-item__error',
  unsavedConfirmButton: '.connection-form-continue-confirm',
  unsavedCancelButton: '.connection-form-continue-cancel',
  confirmDialog: '.el-message-box',
  deleteConfirmButton: '.el-popper .el-button--primary',
  connectionItemBox: '.connection-item-box',
  connectionItemDeleteBox: '.connection-item-delete-box',
} as const;

export const shellSelectors = {
  userDropdown: '[id^="layout-header-user-"]',
  logoutMenuItem: '#layout-header-logout',
  logoutConfirmButton: '.logout-confirm',
  layoutMenu: '[data-testid="layout-menu"], .layout-menu',
} as const;

export const measurementManagementSelectors = {
  page: '[data-testid="measurement-management-page"], .database-page-container',
  sidePanel: '[data-testid="measurement-management-side-panel"], .database-list-wrapper',
  detailPanel: '[data-testid="measurement-management-detail-panel"], .database-details-wrapper',
  treeWrapper: '[data-testid="measurement-tree-wrapper"], .measurement-tree-wrapper',
  treeSearchInput: '[data-testid="measurement-tree-search"], #measurement-tree-input',
  treeRefreshButton: '[data-testid="measurement-tree-refresh"], #measurement-tree-refresh',
  treeBox: '[data-testid="measurement-tree-box"], .measurement-tree-box',
  treeRootMoreButton: '#tree-node-root-more',
  treeRootAllButton: '#tree-node-root-all',
  contextMenu: '[data-testid="measurement-context-menu"], .context-menu-container',
  contextMenuNewDatabase: '[data-testid="measurement-context-menu-new-database"]',
  contextMenuNewMeasurement: '[data-testid="measurement-context-menu-new-measurement"]',
  contextMenuDelete: '[data-testid="measurement-context-menu-delete"]',
  databaseModal: '[data-testid="measurement-database-modal"], #new-database-modal-database',
  databaseModalName: '[data-testid="measurement-database-modal-name"], #new-database-modal-groupName',
  databaseModalConfirm: '[data-testid="measurement-database-modal-confirm"], #new-database-modal-confirm',
  measurementModal: '[data-testid="measurement-modal"], #measurement-modal-measurement',
  measurementModalConfirm: '[data-testid="measurement-modal-confirm"], #measurement-modal-confirm',
  measurementModalCancel: '[data-testid="measurement-modal-cancel"], #measurement-modal-cancel',
  measurementModalAddRow: '[data-testid="measurement-modal-add-row"], #measurement-modal-collapse-add',
  databaseDetail: '[data-testid="measurement-database-detail"], .database-detail-wrapper',
  databaseDetailAddMeasurement: '#mesaurement-add',
  databaseDetailTable: '.database-detail-wrapper .el-table',
  databaseInfoTitle: '.database-detail-wrapper .info-title',
  databaseInfoDeviceCount: '#device-total-li',
  databaseInfoMeasurementCount: '#measurement-total-li',
  databaseDeleteButton: '#mesaurement-top-delete-databse',
  databaseSearchInput: '#mesaurement-search',
  databaseSearchType: '#measurement-search-type',
  databaseSearchTypeName: '#measurement-search-type-name',
  databaseSearchTypeDescription: '#measurement-search-type-description',
  databaseImportButton: '#mesaurement-import',
  databaseExportDropdown: '#mesaurement-download-dropdown',
  databaseExportButton: '#mesaurement-download',
  databaseExportCsv: '#mesaurement-download-csv',
  databaseExportXlsx: '#mesaurement-download-xlsx',
  databaseBatchDeleteButton: '#mesaurement-batch-del',
  databaseRefreshButton: '#mesaurement-refresh',
  columnFilterButton: '#measurement-column-filter',
  columnFilterPopover: '.col-filter-popover-box',
  columnFilterConfirm: '#measurement-column-checkbox-confirm',
  columnFilterAliasCheckbox: '#measurement-column-checkbox-alias',
  columnFilterAll: '#measurement-column-checkbox-all',
  columnFilterReset: '#measurement-column-checkbox-reset',
  importModal: '#measurement-modal-import',
  importUpload: '#measurement-import-upload',
  importNextButton: '#measurement-import-next',
  importCloseButton: '#measurement-import-close',
  measurementModalDeleteConfirm: '.measurement-modal-collapse-del-confirm',
  deleteConfirmButton: '.el-message-box .el-button--primary',
  deleteConfirmDialog: '.el-message-box',
  menuSubmenu: '[data-testid="layout-submenu-measurement-management"]',
  menuSubmenuTitle: '[data-testid="layout-submenu-title-measurement-management"]',
  menuMeasurementList: '[data-testid="layout-menu-item-measurement-management-list"]',
  menuDataModel: '[data-testid="layout-menu-item-measurement-management-model"]',
  modelPage: '[data-testid="measurement-model-page"], .page-container:has(#measurement-tree-doc)',
  modelTitle: '[data-testid="measurement-model-title"], .detail-title-text',
  modelToolbar: '[data-testid="measurement-model-toolbar"], .operate-buttons',
  modelDocButton: '[data-testid="measurement-model-doc"], #measurement-tree-doc',
  modelRefreshButton: '[data-testid="measurement-model-refresh"], #measurement-tree-refresh',
  modelContainer: '[data-testid="measurement-model-container"], .model-container',
  modelChartWrapper: '[data-testid="measurement-model-chart-wrapper"], .chart-container-box',
  modelChart: '[data-testid="measurement-model-chart"]',
} as const;

export const feedbackSelectors = {
  successToast: '.el-message--success',
  errorToast: '.el-message--error',
} as const;
