const keywords = [
  'ADD',
  'AFTER',
  'ALIAS',
  'ALIGN',
  'ALIGNED',
  'ALL',
  'ALTER',
  'ALTER_TIMESERIES',
  'ANY',
  'APPEND',
  'APPLY_TEMPLATE',
  'AS',
  'ASC',
  'ATTRIBUTES',
  'BEFORE',
  'BEGIN',
  'BLOCKED',
  'BOUNDARY',
  'BY',
  'CACHE',
  'CHILD',
  'CLEAR',
  'CLUSTER',
  'CONCAT',
  'CONFIGNODES',
  'CONFIGURATION',
  'CONTINUOUS',
  'COUNT',
  'CONTAIN',
  'CQ',
  'CQS',
  'CREATE',
  'CREATE_CONTINUOUS_QUERY',
  'CREATE_FUNCTION',
  'CREATE_ROLE',
  'CREATE_TIMESERIES',
  'CREATE_TRIGGER',
  'CREATE_USER',
  'DATA',
  'DATABASE',
  'DATABASES',
  'DATANODES',
  'DEACTIVATE',
  'DEBUG',
  'DELETE',
  'DELETE_ROLE',
  'DELETE_STORAGE_GROUP',
  'DELETE_TIMESERIES',
  'DELETE_USER',
  'DESC',
  'DESCRIBE',
  'DEVICE',
  'DEVICES',
  'DISABLE',
  'DISCARD',
  'DROP',
  'DROP_CONTINUOUS_QUERY',
  'DROP_FUNCTION',
  'DROP_TRIGGER',
  'END',
  'ENDTIME',
  'EVERY',
  'EXPLAIN',
  'FILL',
  'FILE',
  'FLUSH',
  'FOR',
  'FROM',
  'FULL',
  'FUNCTION',
  'FUNCTIONS',
  'GLOBAL',
  'GRANT',
  'GRANT_ROLE_PRIVILEGE',
  'GRANT_USER_PRIVILEGE',
  'GRANT_USER_ROLE',
  'GROUP',
  'HAVING',
  'INDEX',
  'INFO',
  'INSERT',
  'INSERT_TIMESERIES',
  'INTO',
  'KILL',
  'LABEL',
  'LAST',
  'LATEST',
  'LEVEL',
  'LIKE',
  'LIMIT',
  'LINEAR',
  'LINK',
  'LIST',
  'LIST_ROLE',
  'LIST_USER',
  'LOAD',
  'LOCAL',
  'LOCK',
  'MERGE',
  'METADATA',
  'MODIFY_PASSWORD',
  'NODES',
  'NONE',
  'NOW',
  'OF',
  'OFF',
  'OFFSET',
  'ON',
  'ORDER',
  'ONSUCCESS',
  'PARTITION',
  'PASSWORD',
  'PATHS',
  'PIPE',
  'PIPES',
  'PIPESINK',
  'PIPESINKS',
  'PIPESINKTYPE',
  'POLICY',
  'PREVIOUS',
  'PREVIOUSUNTILLAST',
  'PRIVILEGES',
  'PROCESSLIST',
  'PROPERTY',
  'PRUNE',
  'QUERIES',
  'QUERY',
  'RANGE',
  'READONLY',
  'READ_TEMPLATE',
  'READ_TEMPLATE_APPLICATION',
  'READ_TIMESERIES',
  'REGEXP',
  'REGIONID',
  'REGIONS',
  'REMOVE',
  'RENAME',
  'RESAMPLE',
  'RESOURCE',
  'REVOKE',
  'REVOKE_ROLE_PRIVILEGE',
  'REVOKE_USER_PRIVILEGE',
  'REVOKE_USER_ROLE',
  'ROLE',
  'RUNNING',
  'SCHEMA',
  'SELECT',
  'SERIESSLOTID',
  'SET',
  'SET_STORAGE_GROUP',
  'SETTLE',
  'SGLEVEL',
  'SHOW',
  'SLIMIT',
  'SOFFSET',
  'STORAGE',
  'START',
  'STARTTIME',
  'STATELESS',
  'STATEFUL',
  'STOP',
  'SYSTEM',
  'TAGS',
  'TASK',
  'TEMPLATE',
  'TIMEOUT',
  'TIMESERIES',
  'TIMESLOTID',
  'TO',
  'TOLERANCE',
  'TOP',
  'TRACING',
  'TRIGGER',
  'TRIGGERS',
  'TTL',
  'UNLINK',
  'UNLOAD',
  'UNSET',
  'UPDATE',
  'UPDATE_TEMPLATE',
  'UPSERT',
  'URI',
  'USER',
  'USING',
  'VALUES',
  'VERIFY',
  'VERSION',
  'WATERMARK_EMBEDDING',
  'WHERE',
  'WITH',
  'WITHOUT',
  'WRITABLE',
  'VIEW',
];

const sqlExamples: { [key: string]: string[] } = {
  SET: ['SET STORAGE GROUP TO <FullPath>', 'SET TTL TO <StorageGroupPath> <Integer>'],
  CREATE: [
    'CREATE TIMESERIES <FullPath> WITH <AttributeClauses>',
    'CREATE TIMESERIES <FullPath> WITH <AttributeClauses> TAGS (<Clauses>) ATTRIBUTES(<Clauses>)',
    'CREATE USER <userName> <password>',
    'CREATE ROLE <roleName>',
  ],
  ALTER: [
    'ALTER TIMESERIES <FullPath> ADD TAGS <Clauses>',
    'ALTER TIMESERIES <FullPath> ADD ATTRIBUTES <Clauses>',
    'ALTER TIMESERIES <FullPath> DROP <TagNames>',
    'ALTER TIMESERIES <FullPath> RENAME <OldName> TO <NewName>',
    'ALTER TIMESERIES <FullPath> SET <Clauses>',
    'ALTER TIMESERIES <FullPath>',
    'ALTER USER <username> SET PASSWORD <password>',
  ],
  DELETE: ['DELETE STORAGE GROUP <PrefixPath>', 'DELETE TIMESERIES <PrefixPath>', 'DELETE FROM <PrefixPath>', 'DELETE FROM <PrefixPath> WHERE <WhereClause>'],
  UNSET: ['UNSET TTL TO <StorageGroupPath>'],
  UPSERT: ['UPSERT ALIAS=<NewName> TAGS(<Clauses>) ATTRIBUTES(<Clauses>)'],
  SHOW: [
    'SHOW STORAGE GROUP',
    'SHOW STORAGE GROUP <PrefixPath>',
    'SHOW TIMESERIES',
    'SHOW TIMESERIES (<PrefixPath>)? Where <WhereClause>',
    'SHOW TIMESERIES (<PrefixPath>)? LIMIT <Integer> OFFSET <Integer>',
    'SHOW LATEST TIMESERIES (<PrefixPath>)?',
    'SHOW DEVICES <PrefixPath> WITH STORAGE GROUP',
    'SHOW ALL TTL',
    'SHOW TTL <StorageGroupNames>',
    'SHOW CHILD PATHS <prefixPath>',
    'SHOW CHILD NODES <prefixPath>',
    'SHOW DEVICES',
    'SHOW DEVICES <PrefixPath>',
    'SHOW DEVICES WITH STORAGE GROUP',
    'SHOW SHOW DEVICES <PrefixPath> WITH STORAGE GROUP',
  ],
  COUNT: ['COUNT TIMESERIES <Path> GROUP BY LEVEL=<Integer>', 'COUNT NODES <PrefixPath> LEVEL=<Integer>'],
  INSERT: ['INSERT INTO <PrefixPath>(TIMESTAMP, <PointNames>) VALUES(<Values>)'],
  SELECT: [
    'SELECT <SelectClause> FROM <FromClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause> GROUP BY <GroupByTimeClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause> FILL <FillClause>',
  ],
  ORDER: ['ORDER BY TIME ASC | DESC'],
  LIMIT: ['LIMIT <Integer> [OFFSET <Integer>]?'],
  SLIMIT: ['SLIMIT <Integer> [OFFSET <Integer>]?'],
  DROP: ['DROP ROLE <roleName>'],
  GRANT: ['GRANT USER <userName> PRIVILEGES <privileges> ON <nodeName>', 'GRANT ROLE <roleName> PRIVILEGES <privileges> ON <nodeName>', 'GRANT <roleName> TO <userName>'],
  REVOKE: ['REVOKE USER <userName> PRIVILEGES <privileges> ON <nodeName>', 'REVOKE ROLE <roleName> PRIVILEGES <privileges> ON <nodeName>', 'REVOKE <roleName> FROM <userName>'],
  LIST: [
    'LIST USER',
    'LIST ROL',
    'LIST PRIVILEGES USER <username> ON <path>',
    'LIST PRIVILEGES ROLE <roleName> ON <path>',
    'LIST USER PRIVILEGES <username>',
    'LIST ROLE PRIVILEGES <roleName>',
    'LIST ALL ROLE OF USER <username>',
    'LIST ALL USER OF ROLE <roleName>',
  ],
};

export { keywords, sqlExamples as selectList };
