const keywords = [
  'ADD',
  'AFTER',
  'ALIAS',
  'ALIGN',
  'ALIGNED',
  'ALL',
  'ALTER',
  'ALTER_TIMESERIES',
  'ANY',
  'APPEND',
  'APPLY_TEMPLATE',
  'AS',
  'ASC',
  'ATTRIBUTES',
  'BEFORE',
  'BEGIN',
  'BLOCKED',
  'BOUNDARY',
  'BY',
  'CACHE',
  'CHILD',
  'CLEAR',
  'CLUSTER',
  'CONCAT',
  'CONFIGNODES',
  'CONFIGURATION',
  'CONTINUOUS',
  'COUNT',
  'CONTAIN',
  'CQ',
  'CQS',
  'CREATE',
  'CREATE_CONTINUOUS_QUERY',
  'CREATE_FUNCTION',
  'CREATE_ROLE',
  'CREATE_TIMESERIES',
  'CREATE_TRIGGER',
  'CREATE_USER',
  'DATA',
  'DATABASE',
  'DATABASES',
  'DATANODES',
  'DEACTIVATE',
  'DEBUG',
  'DELETE',
  'DELETE_ROLE',
  'DELETE_STORAGE_GROUP',
  'DELETE_TIMESERIES',
  'DELETE_USER',
  'DESC',
  'DESCRIBE',
  'DEVICE',
  'DEVICES',
  'DISABLE',
  'DISCARD',
  'DROP',
  'DROP_CONTINUOUS_QUERY',
  'DROP_FUNCTION',
  'DROP_TRIGGER',
  'END',
  'ENDTIME',
  'EVERY',
  'EXPLAIN',
  'FILL',
  'FILE',
  'FLUSH',
  'FOR',
  'FROM',
  'FULL',
  'FUNCTION',
  'FUNCTIONS',
  'GLOBAL',
  'GRANT',
  'GRANT_ROLE_PRIVILEGE',
  'GRANT_USER_PRIVILEGE',
  'GRANT_USER_ROLE',
  'GROUP',
  'HAVING',
  'INDEX',
  'INFO',
  'INSERT',
  'INSERT_TIMESERIES',
  'INTO',
  'KILL',
  'LABEL',
  'LAST',
  'LATEST',
  'LEVEL',
  'LIKE',
  'LIMIT',
  'LINEAR',
  'LINK',
  'LIST',
  'LIST_ROLE',
  'LIST_USER',
  'LOAD',
  'LOCAL',
  'LOCK',
  'MERGE',
  'METADATA',
  'MODIFY_PASSWORD',
  'NODES',
  'NONE',
  'NOW',
  'OF',
  'OFF',
  'OFFSET',
  'ON',
  'ORDER',
  'ONSUCCESS',
  'PARTITION',
  'PASSWORD',
  'PATHS',
  'PIPE',
  'PIPES',
  'PIPESINK',
  'PIPESINKS',
  'PIPESINKTYPE',
  'POLICY',
  'PREVIOUS',
  'PREVIOUSUNTILLAST',
  'PRIVILEGES',
  'PROCESSLIST',
  'PROPERTY',
  'PRUNE',
  'QUERIES',
  'QUERY',
  'RANGE',
  'READONLY',
  'READ_TEMPLATE',
  'READ_TEMPLATE_APPLICATION',
  'READ_TIMESERIES',
  'REGEXP',
  'REGIONID',
  'REGIONS',
  'REMOVE',
  'RENAME',
  'RESAMPLE',
  'RESOURCE',
  'REVOKE',
  'REVOKE_ROLE_PRIVILEGE',
  'REVOKE_USER_PRIVILEGE',
  'REVOKE_USER_ROLE',
  'ROLE',
  'RUNNING',
  'SCHEMA',
  'SELECT',
  'SERIESSLOTID',
  'SET',
  'SET_STORAGE_GROUP',
  'SETTLE',
  'SGLEVEL',
  'SHOW',
  'SLIMIT',
  'SOFFSET',
  'STORAGE',
  'START',
  'STARTTIME',
  'STATELESS',
  'STATEFUL',
  'STOP',
  'SYSTEM',
  'TAGS',
  'TASK',
  'TEMPLATE',
  'TIMEOUT',
  'TIMESERIES',
  'TIMESLOTID',
  'TO',
  'TOLERANCE',
  'TOP',
  'TRACING',
  'TRIGGER',
  'TRIGGERS',
  'TTL',
  'UNLINK',
  'UNLOAD',
  'UNSET',
  'UPDATE',
  'UPDATE_TEMPLATE',
  'UPSERT',
  'URI',
  'USER',
  'USING',
  'VALUES',
  'VERIFY',
  'VERSION',
  'WATERMARK_EMBEDDING',
  'WHERE',
  'WITH',
  'WITHOUT',
  'WRITABLE',
  'VIEW',
];
const tableKeywords = [
  'ALTER',
  'AND',
  'AS',
  'BETWEEN',
  'BY',
  'CASE',
  'CAST',
  'CONSTRAINT',
  'CREATE',
  'CROSS',
  'CUBE',
  'CURRENT_CATALOG',
  'CURRENT_DATE',
  'CURRENT_PATH',
  'CURRENT_ROLE',
  'CURRENT_SCHEMA',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'CURRENT_USER',
  'DEALLOCATE',
  'DELETE',
  'DESCRIBE',
  'DISTINCT',
  'DROP',
  'ELSE',
  'END',
  'ESCAPE',
  'EXCEPT',
  'EXISTS',
  'EXTRACT',
  'FALSE',
  'FOR',
  'FROM',
  'FULL',
  'GROUP',
  'GROUPING',
  'HAVING',
  'IN',
  'INNER',
  'INSERT',
  'INTERSECT',
  'INTO',
  'IS',
  'JOIN',
  'JSON_ARRAY',
  'JSON_EXISTS',
  'JSON_OBJECT',
  'JSON_QUERY',
  'JSON_TABLE',
  'JSON_VALUE',
  'LEFT',
  'LIKE',
  'LISTAGG',
  'LOCALTIME',
  'LOCALTIMESTAMP',
  'NATURAL',
  'NORMALIZE',
  'NOT',
  'NULL',
  'ON',
  'OR',
  'ORDER',
  'OUTER',
  'PREPARE',
  'RECURSIVE',
  'RIGHT',
  'ROLLUP',
  'SELECT',
  'SKIP',
  'TABLE',
  'THEN',
  'TRIM',
  'TRUE',
  'UESCAPE',
  'UNION',
  'UNNEST',
  'USING',
  'VALUES',
  'WHEN',
  'WHERE',
  'WITH',
  'FILL',
].concat([
  'SHOW',
  'USE',
  'DESC',
  'DESCRIBE',
  'INSERT',
  'UPDATE',
  'DELETE',
  'CREATE',
  'ALTER',
  'DROP',
  'GRANT',
  'REVOKE',
  'LIST',
  'SET',
  'EXPLAIN',
  'TABLE',
  'DATABASE',
  'DATABASES',
  'TABLES',
  'CURRENT_DATABASE',
]);
const sqlExamples: { [key: string]: string[] } = {
  SET: ['SET STORAGE GROUP TO <FullPath>', 'SET TTL TO <StorageGroupPath> <Integer>'],
  CREATE: [
    'CREATE TIMESERIES <FullPath> WITH <AttributeClauses>',
    'CREATE TIMESERIES <FullPath> WITH <AttributeClauses> TAGS (<Clauses>) ATTRIBUTES(<Clauses>)',
    'CREATE USER <userName> <password>',
    'CREATE ROLE <roleName>',
  ],
  ALTER: [
    'ALTER TIMESERIES <FullPath> ADD TAGS <Clauses>',
    'ALTER TIMESERIES <FullPath> ADD ATTRIBUTES <Clauses>',
    'ALTER TIMESERIES <FullPath> DROP <TagNames>',
    'ALTER TIMESERIES <FullPath> RENAME <OldName> TO <NewName>',
    'ALTER TIMESERIES <FullPath> SET <Clauses>',
    'ALTER TIMESERIES <FullPath>',
    'ALTER USER <username> SET PASSWORD <password>',
  ],
  DELETE: ['DELETE STORAGE GROUP <PrefixPath>', 'DELETE TIMESERIES <PrefixPath>', 'DELETE FROM <PrefixPath>', 'DELETE FROM <PrefixPath> WHERE <WhereClause>'],
  UNSET: ['UNSET TTL TO <StorageGroupPath>'],
  UPSERT: ['UPSERT ALIAS=<NewName> TAGS(<Clauses>) ATTRIBUTES(<Clauses>)'],
  SHOW: [
    'SHOW STORAGE GROUP',
    'SHOW STORAGE GROUP <PrefixPath>',
    'SHOW TIMESERIES',
    'SHOW TIMESERIES (<PrefixPath>)? Where <WhereClause>',
    'SHOW TIMESERIES (<PrefixPath>)? LIMIT <Integer> OFFSET <Integer>',
    'SHOW LATEST TIMESERIES (<PrefixPath>)?',
    'SHOW DEVICES <PrefixPath> WITH STORAGE GROUP',
    'SHOW ALL TTL',
    'SHOW TTL <StorageGroupNames>',
    'SHOW CHILD PATHS <prefixPath>',
    'SHOW CHILD NODES <prefixPath>',
    'SHOW DEVICES',
    'SHOW DEVICES <PrefixPath>',
    'SHOW DEVICES WITH STORAGE GROUP',
    'SHOW SHOW DEVICES <PrefixPath> WITH STORAGE GROUP',
  ],
  COUNT: ['COUNT TIMESERIES <Path> GROUP BY LEVEL=<Integer>', 'COUNT NODES <PrefixPath> LEVEL=<Integer>'],
  INSERT: ['INSERT INTO <PrefixPath>(TIMESTAMP, <PointNames>) VALUES(<Values>)'],
  SELECT: [
    'SELECT <SelectClause> FROM <FromClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause> GROUP BY <GroupByTimeClause>',
    'SELECT <SelectClause> FROM <FromClause> WHERE <WhereClause> FILL <FillClause>',
  ],
  ORDER: ['ORDER BY TIME ASC | DESC'],
  LIMIT: ['LIMIT <Integer> [OFFSET <Integer>]?'],
  SLIMIT: ['SLIMIT <Integer> [OFFSET <Integer>]?'],
  DROP: ['DROP ROLE <roleName>'],
  GRANT: ['GRANT USER <userName> PRIVILEGES <privileges> ON <nodeName>', 'GRANT ROLE <roleName> PRIVILEGES <privileges> ON <nodeName>', 'GRANT <roleName> TO <userName>'],
  REVOKE: ['REVOKE USER <userName> PRIVILEGES <privileges> ON <nodeName>', 'REVOKE ROLE <roleName> PRIVILEGES <privileges> ON <nodeName>', 'REVOKE <roleName> FROM <userName>'],
  LIST: [
    'LIST USER',
    'LIST ROL',
    'LIST PRIVILEGES USER <username> ON <path>',
    'LIST PRIVILEGES ROLE <roleName> ON <path>',
    'LIST USER PRIVILEGES <username>',
    'LIST ROLE PRIVILEGES <roleName>',
    'LIST ALL ROLE OF USER <username>',
    'LIST ALL USER OF ROLE <roleName>',
  ],
};

const tableSqlExamples: { [key: string]: string[] } = {
  USE: ['USE <DATABASE_NAME>'],
  CREATE: [
    'CREATE DATABASE (IF NOT EXISTS)? <DATABASE_NAME> (WITH properties)?',
    "CREATE TABLE (IF NOT EXISTS)? qualifiedName'(' (identifier type (columnCategory=(TAG | ATTRIBUTE | TIME | FIELD))? charsetName? comment? (',' identifier type (columnCategory=(TAG | ATTRIBUTE | TIME | FIELD))? charsetName? comment?)*)? ')' charsetDesc? comment? (WITH properties)? ;",
    'CREATE USER <USERNAME> <PASSWORD>',
    'CREATE ROLE <ROLENAME>',
  ],
  ALTER: [
    'ALTER DATABASE (IF EXISTS)? database=identifier SET PROPERTIES propertyAssignments',
    "ALTER TABLE (IF EXISTS)? tableName=qualifiedName ADD COLUMN (IF NOT EXISTS)? column=columnDefinition COMMENT 'column_comment' ",
    'ALTER TABLE (IF EXISTS)? tableName=qualifiedName DROP COLUMN (IF EXISTS)? column=identifier',
    'ALTER TABLE (IF EXISTS)? tableName=qualifiedName SET PROPERTIES propertyAssignments',
    'ALTER USER <USERNAME> SET PASSWORD <password>',
  ],
  DESC: ['(DESC | DESCRIBE) <TABLE_NAME> (DETAILS)?'],
  DROP: ['DROP DATABASE (IF EXISTS)? <DATABASE_NAME>', 'DROP TABLE (IF EXISTS)? <TABLE_NAME>', 'DROP USER <USERNAME>', 'DROP ROLE <ROLENAME>'],
  DELETE: ['DELETE FROM <TABLE_NAME> [WHERE DELETE_CONDITION]?'],
  UPDATE: ['UPDATE <TABLE_NAME> SET updateAssignment (', ' updateAssignment)* (WHERE where=booleanExpression)?'],
  SHOW: ['SHOW DATABASES (DETAILS)?', 'SHOW CURRENT_DATABASE', 'SHOW TABLES (DETAILS)? ((FROM | IN) database_name)?'],
  INSERT: ['INSERT INTO <TABLE_NAME> [(COLUMN_NAME[, COLUMN_NAME]*)]? VALUES (COLUMN_VALUE[, COLUMN_VALUE]*)'],
  SELECT: [
    'SELECT ⟨select_list⟩ FROM ⟨tables⟩',
    'SELECT ⟨select_list⟩ FROM ⟨tables⟩ WHERE ⟨condition⟩',
    'SELECT ⟨select_list⟩ FROM ⟨tables⟩ WHERE ⟨condition⟩ GROUP BY ⟨groups⟩ HAVING ⟨group_filter⟩ FILL ⟨fill_methods⟩ ORDER BY ⟨order_expression⟩ OFFSET ⟨n⟩ LIMIT ⟨n⟩',
  ],
  ORDER: ['ORDER BY TIME ASC | DESC'],
  LIMIT: ['LIMIT <Integer> [OFFSET <Integer>]?'],
  GRANT: [
    'GRANT ROLE <ROLENAME> TO <USERNAME>',
    'GRANT <PRIVILEGES> ON <DATABASE>.<TABLENAME> TO USER <USERNAME> [WITH GRANT OPTION]',
    'GRANT <PRIVILEGES> ON <DATABASE>.<TABLENAME> TO ROLE <ROLENAME>',
  ],
  REVOKE: ['REVOKE ROLE <ROLENAME> FROM <USERNAME>', 'REVOKE <PRIVILEGES> ON <DATABASE>.<TABLENAME> FROM USER <USERNAME>', 'REVOKE <PRIVILEGES> ON <DATABASE>.<TABLENAME> FROM ROLE <ROLENAME>'],
  LIST: ['LIST USER', 'LIST ROLE', 'LIST USER OF ROLE <ROLENAME>', 'LIST ROLE OF USER <USERNAME>', 'LIST PRIVILEGES OF USER <USERNAME>', 'LIST PRIVILEGES OF ROLE <ROLENAME>'],
};

export { keywords, sqlExamples as selectList, tableKeywords, tableSqlExamples as tableSelectList };
